// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Admin struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Cataloge struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	ParentID  int32  `json:"parent_id"`
	SortOrder int16  `json:"sort_order"`
}

type Producte struct {
	ID        int32  `json:"id"`
	CatalogID int32  `json:"catalog_id"`
	Name      string `json:"name"`
	Price     int32  `json:"price"`
	Content   string `json:"content"`
	Discount  int32  `json:"discount"`
	ImageLink string `json:"image_link"`
	ImageList string `json:"image_list"`
	Created   int32  `json:"created"`
	View      int32  `json:"view"`
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Address  string `json:"address"`
	Password string `json:"password"`
	Created  int32  `json:"created"`
}
